name-template: 'Release draft'
tag-template: 'draft'
categories:
  - title: 'ğŸš€ Features'
    labels:
      - 'type:feature'
  - title: 'ğŸ› Bug Fixes'
    labels:
      - 'type:bug'
  - title: 'ğŸ§° Maintenance and others'
    labels: 
      - 'type:test'
      - 'scope:infrastructure'
      - 'type:refactoring'
      - 'scope:docs'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&'
template: |
  [Milestone with issues list](https://github.com/lisa-analyzer/lisa/milestone/###MILESTONE_NUMBER###) 
  [Maven (sdk)](https://search.maven.org/artifact/io.github.lisa-analyzer/lisa-sdk/###TARGET_VERSION###/jar) - [Maven (core)](https://search.maven.org/artifact/io.github.lisa-analyzer/lisa-core/###TARGET_VERSION###/jar) - [Maven (imp)](https://search.maven.org/artifact/io.github.lisa-analyzer/lisa-imp/###TARGET_VERSION###/jar)
  [Javadoc (sdk)](https://javadoc.io/doc/io.github.lisa-analyzer/lisa-sdk/###TARGET_VERSION###) - [Javadoc (core)](https://javadoc.io/doc/io.github.lisa-analyzer/lisa-core/###TARGET_VERSION###) - [Javadoc (imp)](https://javadoc.io/doc/io.github.lisa-analyzer/lisa-imp/###TARGET_VERSION###)
  
  ## Changes

  $CHANGES
